require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TinyYego' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  target 'TinyYegoTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
end
